call db_ui#utils#set_mapping('<C-]>', '<Plug>(DBUI_JumpToForeignKey)')
call db_ui#utils#set_mapping('vic', '<Plug>(DBUI_YankCellValue)')
call db_ui#utils#set_mapping('yic', '<Plug>(DBUI_YankCellValue)y')
call db_ui#utils#set_mapping('yh', '<Plug>(DBUI_YankHeader)')
call db_ui#utils#set_mapping('<localleader>R', '<Plug>(DBUI_ToggleResultLayout)')
